pipeline {
	agent any
	tools {
	  maven 'Maven 3.5'
	  git 'Default'
	  jdk 'Java 10'
	}
	stages {
	    stage("just Trying") {
	    	steps {
	        	echo 'Hello World'
	        }   
	    }
	    stage("Maven Build & JUnit Tests") {
	    	steps {
	    		sh 'mvn -f /home/ec2-user/workspace/DemoPipeline/javaApp/pom.xml clean package'
	    	}
	    }
	    stage("Delivery") {
	    	steps {
	    		echo 'Doing stuff on the server... probably'
	    	}
	    }
	    stage("Selenium Test") {
	    	steps {
			sh 'mvn -f /home/ec2-user/workspace/DemoPipeline/javaApp/pom.xml pre-integration-test'
			sh 'mvn -f /home/ec2-user/workspace/DemoPipeline/javaApp/pom.xml failsafe:integration-test'
			sh 'mvn -f /home/ec2-user/workspace/DemoPipeline/javaApp/pom.xml post-integration-test'
	    		sh 'mvn -f /home/ec2-user/workspace/DemoPipeline/javaApp/pom.xml failsafe:verify'
	    	}
	    }
	    stage("Emailing") {
	    	steps {
	    		echo 'You get an email, and you, and you...'
	    	}
	    }
    }
}
