pipeline {
	agent any
	tools {
	  maven 'Maven 3.5'
	  git 'Default'
	  jdk 'Java 10'
	}
	stages {
	    stage("just Trying") {
	    	steps {
	        	echo 'Hello World'
	        }   
	    }
	    stage("Maven Build") {
	    	steps {
	    		sh '/home/ec2-user/workspace/DemoPipeline/javaApp mvn clean install'
	    	}
	    }
    }
}